[package]
name = "websocket-example"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.21"
wtransport = "0.1.0"
tokio = { version = "1.28.1",  features = ["full"] }
