apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong
        image: myregistry/ping-pong:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong
spec:
  selector:
    app: ping-pong
  ports:
  - name: http
    port: 80
    targetPort: 8000
  type: LoadBalancer
